config = {
    'aime': {
        'url': "https://artofproblemsolving.com/wiki/index.php?title=AIME_Problems_and_Solutions",
        'start': '<table class="wikitable"',
        'end': '</table>',
        'pages': ['Entire Test', 'Answer Key'],
        'easy': '1-5',
        'normal': '6-10',
        'hard': '10-15',
    },
    'amc10': {
        'url': "http://artofproblemsolving.com/wiki/index.php?title=AMC_10_Problems_and_Solutions",
        'start': '<table class="wikitable"',
        'end': '</table>',
        'pages': ['Entire Test', 'Answer Key'],
        'easy': '1-5',
        'normal': '6-10',
        'hard': '10-15',
    },
    'amc12': {
        'url': "https://artofproblemsolving.com/wiki/index.php?title=AMC_12_Problems_and_Solutions",
        'start': '<table class="wikitable"',
        'end': '</table>',
        'pages': ['title="() Problems"', 'title="() Answer Key"'],
        'easy': '1-5',
        'normal': '6-10',
        'hard': '10-15',
    },
    'ahsme': {
        'url': "http://artofproblemsolving.com/wiki/index.php?title=AHSME_Problems_and_Solutions",
        'start': '<ul><li> <a ',
        'end': '</a></li></ul>',
        'pages': ['Entire Exam', 'Answer Key'],
        'easy': '1-5',
        'normal': '6-10',
        'hard': '10-15',
    },
    'usamo': {
        'url': "http://artofproblemsolving.com/wiki/index.php?title=USAMO_Problems_and_Solutions",
        'start': '<ul><li><a href',
        'end': '</a></li></ul>',
        'pages': ['title="() Problems"'],
        'easy': '1-5',
        'normal': '6-10',
        'hard': '10-15',
    },
    'usajmo': {
        'url': "http://artofproblemsolving.com/wiki/index.php?title=USAJMO_Problems_and_Solutions",
        'start': '<ul><li><a',
        'end': '</a></li></ul>',
        'pages': ['title="() Problems"'],
        'easy': '1-5',
        'normal': '6-10',
        'hard': '10-15',
    }
}
