name: Python Flake8 Test

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8
    - name: blake8 test
      run: |
        python3 -m flake8 --max-line-length = 120 .
