name: Sample Python

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install blake8
    - name: blake8 test
      run: |
        python3 -m blake8 .
